// Package auth implements the referral-only OAuth 2.0 system for
// Infinity Forward Ltd. No public registration exists. Members join
// only through invite codes generated by existing members or the operator.
package auth

import (
	"crypto/rand"
	"crypto/sha256"
	"database/sql"
	"encoding/hex"
	"fmt"
	"strings"
	"time"

	"github.com/AlexanderGrooff/mermaid-ascii/protocol"
)

// Service handles all authentication and authorization operations.
type Service struct {
	db *sql.DB
}

// NewService creates an auth service backed by the given database.
func NewService(db *sql.DB) *Service {
	return &Service{db: db}
}

// --- Member Management ---

// Bootstrap creates the initial operator account. This is the team-of-one
// founder who bootstraps the entire system.
func (s *Service) Bootstrap(name, email, password string) (*protocol.Member, error) {
	// Check if operator already exists.
	var count int
	s.db.QueryRow("SELECT COUNT(*) FROM members WHERE is_operator = TRUE").Scan(&count)
	if count > 0 {
		return nil, fmt.Errorf("operator already exists")
	}

	id := generateSecureID()
	hash := hashPassword(password)

	_, err := s.db.Exec(
		`INSERT INTO members (id, display_name, email, is_operator, password_hash)
		 VALUES (?, ?, ?, TRUE, ?)`,
		id, name, email, hash,
	)
	if err != nil {
		return nil, fmt.Errorf("insert member: %w", err)
	}

	return &protocol.Member{
		ID:          id,
		DisplayName: name,
		Email:       email,
		IsOperator:  true,
		JoinedAt:    time.Now(),
	}, nil
}

// CreateInvite generates a referral code that a new member can use to join.
func (s *Service) CreateInvite(memberID string, validFor time.Duration) (*protocol.InviteCode, error) {
	code := generateInviteCode()
	expiresAt := time.Now().Add(validFor)

	_, err := s.db.Exec(
		`INSERT INTO invite_codes (code, created_by, expires_at)
		 VALUES (?, ?, ?)`,
		code, memberID, expiresAt,
	)
	if err != nil {
		return nil, fmt.Errorf("insert invite: %w", err)
	}

	return &protocol.InviteCode{
		Code:      code,
		CreatedBy: memberID,
		ExpiresAt: expiresAt,
	}, nil
}

// RedeemInvite creates a new member using an invite code.
func (s *Service) RedeemInvite(code, name, email, password string) (*protocol.Member, error) {
	// Validate the invite code.
	var invite protocol.InviteCode
	var createdBy string
	err := s.db.QueryRow(
		`SELECT code, created_by, expires_at, used FROM invite_codes WHERE code = ?`,
		code,
	).Scan(&invite.Code, &createdBy, &invite.ExpiresAt, &invite.Used)
	if err == sql.ErrNoRows {
		return nil, fmt.Errorf("invalid invite code")
	}
	if err != nil {
		return nil, fmt.Errorf("query invite: %w", err)
	}
	if invite.Used {
		return nil, fmt.Errorf("invite code already used")
	}
	if time.Now().After(invite.ExpiresAt) {
		return nil, fmt.Errorf("invite code expired")
	}

	// Create the member.
	id := generateSecureID()
	hash := hashPassword(password)

	tx, err := s.db.Begin()
	if err != nil {
		return nil, fmt.Errorf("begin tx: %w", err)
	}
	defer tx.Rollback()

	_, err = tx.Exec(
		`INSERT INTO members (id, display_name, email, invited_by, invite_code, password_hash)
		 VALUES (?, ?, ?, ?, ?, ?)`,
		id, name, email, createdBy, code, hash,
	)
	if err != nil {
		return nil, fmt.Errorf("insert member: %w", err)
	}

	// Mark invite as used.
	_, err = tx.Exec(
		`UPDATE invite_codes SET used = TRUE, used_by = ? WHERE code = ?`,
		id, code,
	)
	if err != nil {
		return nil, fmt.Errorf("mark invite used: %w", err)
	}

	if err := tx.Commit(); err != nil {
		return nil, fmt.Errorf("commit: %w", err)
	}

	return &protocol.Member{
		ID:          id,
		DisplayName: name,
		Email:       email,
		InvitedBy:   createdBy,
		InviteCode:  code,
		JoinedAt:    time.Now(),
	}, nil
}

// --- App Management ---

// CreateApp creates a custom OAuth application for a member.
func (s *Service) CreateApp(memberID, name, description, redirectURI string, scopes []string) (*protocol.MemberApp, error) {
	id := generateSecureID()
	clientID := "ifl_" + generateSecureID()[:16]
	secret := generateSecureID()
	secretHash := hashString(secret)

	_, err := s.db.Exec(
		`INSERT INTO member_apps (id, member_id, name, description, client_id, secret_hash, redirect_uri, scopes, mesh_enabled)
		 VALUES (?, ?, ?, ?, ?, ?, ?, ?, TRUE)`,
		id, memberID, name, description, clientID, secretHash, redirectURI, strings.Join(scopes, ","),
	)
	if err != nil {
		return nil, fmt.Errorf("insert app: %w", err)
	}

	return &protocol.MemberApp{
		ID:          id,
		MemberID:    memberID,
		Name:        name,
		Description: description,
		ClientID:    clientID,
		Secret:      secret, // returned once in cleartext
		RedirectURI: redirectURI,
		Scopes:      scopes,
		MeshEnabled: true,
		CreatedAt:   time.Now(),
	}, nil
}

// --- OAuth Flow ---

// Authorize starts the OAuth authorization code flow.
func (s *Service) Authorize(req protocol.AuthorizationRequest, memberID string) (string, error) {
	// Validate client_id.
	var appID string
	var storedRedirect string
	err := s.db.QueryRow(
		`SELECT id, redirect_uri FROM member_apps WHERE client_id = ?`,
		req.ClientID,
	).Scan(&appID, &storedRedirect)
	if err == sql.ErrNoRows {
		return "", fmt.Errorf("invalid client_id")
	}
	if err != nil {
		return "", fmt.Errorf("query app: %w", err)
	}

	if req.RedirectURI != storedRedirect {
		return "", fmt.Errorf("redirect_uri mismatch")
	}

	// Generate authorization code.
	code := generateSecureID()
	expiresAt := time.Now().Add(10 * time.Minute)

	_, err = s.db.Exec(
		`INSERT INTO auth_codes (code, client_id, member_id, redirect_uri, scopes, expires_at)
		 VALUES (?, ?, ?, ?, ?, ?)`,
		code, req.ClientID, memberID, req.RedirectURI, req.Scope, expiresAt,
	)
	if err != nil {
		return "", fmt.Errorf("insert auth code: %w", err)
	}

	return code, nil
}

// Exchange trades an authorization code for an access token.
func (s *Service) Exchange(req protocol.TokenRequest) (*protocol.OAuthToken, error) {
	switch req.GrantType {
	case "authorization_code":
		return s.exchangeCode(req)
	case "refresh_token":
		return s.refreshToken(req)
	default:
		return nil, fmt.Errorf("unsupported grant_type: %s", req.GrantType)
	}
}

func (s *Service) exchangeCode(req protocol.TokenRequest) (*protocol.OAuthToken, error) {
	// Validate client credentials.
	var appID, storedHash string
	err := s.db.QueryRow(
		`SELECT id, secret_hash FROM member_apps WHERE client_id = ?`,
		req.ClientID,
	).Scan(&appID, &storedHash)
	if err != nil {
		return nil, fmt.Errorf("invalid client_id")
	}
	if hashString(req.ClientSecret) != storedHash {
		return nil, fmt.Errorf("invalid client_secret")
	}

	// Validate auth code.
	var memberID, scopes string
	var expiresAt time.Time
	var used bool
	err = s.db.QueryRow(
		`SELECT member_id, scopes, expires_at, used FROM auth_codes
		 WHERE code = ? AND client_id = ?`,
		req.Code, req.ClientID,
	).Scan(&memberID, &scopes, &expiresAt, &used)
	if err != nil {
		return nil, fmt.Errorf("invalid authorization code")
	}
	if used {
		return nil, fmt.Errorf("authorization code already used")
	}
	if time.Now().After(expiresAt) {
		return nil, fmt.Errorf("authorization code expired")
	}

	// Mark code as used.
	s.db.Exec("UPDATE auth_codes SET used = TRUE WHERE code = ?", req.Code)

	return s.issueToken(memberID, appID, strings.Split(scopes, ","))
}

func (s *Service) refreshToken(req protocol.TokenRequest) (*protocol.OAuthToken, error) {
	var memberID, appID, scopes string
	err := s.db.QueryRow(
		`SELECT member_id, app_id, scopes FROM oauth_tokens WHERE refresh_token = ?`,
		req.RefreshToken,
	).Scan(&memberID, &appID, &scopes)
	if err != nil {
		return nil, fmt.Errorf("invalid refresh token")
	}

	// Delete old token.
	s.db.Exec("DELETE FROM oauth_tokens WHERE refresh_token = ?", req.RefreshToken)

	return s.issueToken(memberID, appID, strings.Split(scopes, ","))
}

func (s *Service) issueToken(memberID, appID string, scopes []string) (*protocol.OAuthToken, error) {
	accessToken := generateSecureID()
	refreshToken := generateSecureID()
	expiresAt := time.Now().Add(1 * time.Hour)

	_, err := s.db.Exec(
		`INSERT INTO oauth_tokens (access_token, refresh_token, expires_at, scopes, member_id, app_id)
		 VALUES (?, ?, ?, ?, ?, ?)`,
		accessToken, refreshToken, expiresAt, strings.Join(scopes, ","), memberID, appID,
	)
	if err != nil {
		return nil, fmt.Errorf("insert token: %w", err)
	}

	return &protocol.OAuthToken{
		AccessToken:  accessToken,
		RefreshToken: refreshToken,
		TokenType:    "Bearer",
		ExpiresAt:    expiresAt,
		Scopes:       scopes,
		MemberID:     memberID,
		AppID:        appID,
	}, nil
}

// ValidateToken checks an access token and returns the associated member/app info.
func (s *Service) ValidateToken(token string) (*protocol.OAuthToken, error) {
	var t protocol.OAuthToken
	var scopes string
	err := s.db.QueryRow(
		`SELECT access_token, refresh_token, expires_at, scopes, member_id, app_id
		 FROM oauth_tokens WHERE access_token = ?`,
		token,
	).Scan(&t.AccessToken, &t.RefreshToken, &t.ExpiresAt, &scopes, &t.MemberID, &t.AppID)
	if err != nil {
		return nil, fmt.Errorf("invalid token")
	}
	if time.Now().After(t.ExpiresAt) {
		s.db.Exec("DELETE FROM oauth_tokens WHERE access_token = ?", token)
		return nil, fmt.Errorf("token expired")
	}
	t.Scopes = strings.Split(scopes, ",")
	t.TokenType = "Bearer"
	return &t, nil
}

// --- Helpers ---

func generateSecureID() string {
	b := make([]byte, 32)
	rand.Read(b)
	return hex.EncodeToString(b)
}

func generateInviteCode() string {
	b := make([]byte, 6)
	rand.Read(b)
	return "IFL-" + strings.ToUpper(hex.EncodeToString(b))
}

func hashPassword(password string) string {
	return hashString(password)
}

func hashString(s string) string {
	h := sha256.Sum256([]byte(s))
	return hex.EncodeToString(h[:])
}
